language: android
dist: trusty
os: linux
jdk: openjdk17

notifications:
  email:
    recipients:
      - davide.capone@studenti.units.it
      - sandrojunior.dellarovere@studenti.units.it
    on_success: always # default: never
    on_failure: always # default: always

env:
  global:
    - ANDROID_API_LEVEL=24
    #- ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools

    - build-tools-23.0.1
    - android-23

    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

install:
  # accept licenses for all available packages that have not already been accepted
  - yes | sdkmanager --licenses >/dev/null

before_install:
  - touch $HOME/.android/repositories.cfg

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_script:
  - chmod +x gradlew

script:
  - chmod +x ./gradlew
  - ./gradlew test