name: SDMProject Gradle Test

on:
  push:
    branches: [ "main", "persistency", "presenter" ]
  pull_request:
    branches: [ "main", "persistency", "presenter" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test

      - name: Test Success
        if: success() 
        run: exit 0

      - name: Test Failure
        if: failure()
        run: exit 1
